name: E2E Tests

on: [pull_request]

permissions: read-all

jobs:
  cypress-run:
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository for cypress tests
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Cypress run
        uses: cypress-io/github-action@c5724eda82337bcff977ce14509f47052c12e04c
        with:
          build: npm run build
          start: npm run preview
