name: SWS Pocket Code Analysis and Firebase Hosting

on:
  push:
    branches: [ main, beta, alpha ]
  pull_request:
    branches: [ main, beta, alpha ]
    
jobs:
  analyze:
    name: Code QL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository for code analysis
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      
  build_and_deploy:
    name: Build ReactApp and Deploy to Firebase Hosting
    if: ${{ github.repository == 'sws2apps/sws-pocket' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/alpha') }}
    runs-on: ubuntu-latest
    needs: [analyze]

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install package dependencies
        run: npm ci

      - name: Run Semantic Release to version and build App
        run: npx semantic-release
        env:
          REACT_APP_ENCRYPTION_KEY: ${{ secrets.REACT_APP_ENCRYPTION_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check if new version has been generated
        id: check_build
        uses: andstor/file-existence-action@v1
        with:
          files: "build"
      
      - name: Deploy to SWS Pocket to Alpha Prerelease
        if: ${{ steps.check_build.outputs.files_exists == 'true' && github.ref == 'refs/heads/alpha' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SWS_POCKET }}'
          channelId: alpha
          projectId: sws-pocket
      
      - name: Deploy to SWS Pocket to Beta Prerelease
        if: ${{ steps.check_build.outputs.files_exists == 'true' && github.ref == 'refs/heads/beta' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SWS_POCKET }}'
          channelId: beta
          projectId: sws-pocket
      
      - name: Deploy to SWS Pocket to Production
        if: ${{ steps.check_build.outputs.files_exists == 'true' && github.ref == 'refs/heads/main' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SWS_POCKET }}'
          channelId: live
          projectId: sws-pocket
