name: CD

on:
  workflow_dispatch:

permissions: read-all

jobs:
  dev_deploy:
    name: Build and Deploy to Development
    if: ${{ github.repository == 'sws2apps/sws-pocket' && github.ref == 'refs/heads/alpha' }}
    environment:
      name: Alpha.env
      url: https://alpha-sws-pocket.web.app
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: alpha
          persist-credentials: false

      - name: Use Node.js current version
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: current

      - name: Install package dependencies
        run: npm ci

      - name: Run Semantic Release to version and build App
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Check if new version has been generated
        id: check_build
        uses: andstor/file-existence-action@f02338908d150e00a4b8bebc2dad18bd9e5229b0
        with:
          files: 'dist'

      - name: Deploy to Firebase
        if: ${{ steps.check_build.outputs.files_exists == 'true' }}
        uses: sws2apps/firebase-deployment@122fee0950b71ab90f1ea7080ae24d00400229ae
        with:
          workloadIdentityProvider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          serviceAccount: ${{ secrets.SERVICE_ACCOUNT }}
          project: alpha-sws-pocket
