name: SWS Pocket Code Check & Deploy to Alpha Environment on Firebase Hosting

on:
  push:
    branches: [ alpha ]
  pull_request:
    branches: [ alpha ]
    
jobs:
  analyze:
    name: Code QL (Alpha)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      
  build_and_preview_on_alpha:
    name: Build ReactApp and Deploy to Firebase Hosting
    if: ${{ github.repository == 'sws2apps/sws-pocket' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [analyze]
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout for alpha environment
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Run Semantic Release to version and build App
        run: npx semantic-release
        env:
          REACT_APP_ENCRYPTION_KEY: ${{ secrets.REACT_APP_ENCRYPTION_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if new version has been generated
        id: check_build
        uses: andstor/file-existence-action@v1
        with:
          files: "build"
      - name: Deploy to SWS Pocket dev environment
        if: steps.check_build.outputs.files_exists == 'true'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SWS_POCKET }}'
          channelId: alpha
          projectId: sws-pocket
